# - name: Get Student Resource Group Information
#   azure_rm_resource_facts:
#     resource_group: "Student{{ item }}"
#     api_version: "2017-12-01"
#   with_sequence: start=0 end="{{ number_students|int -1 }}"

- name: Create a Azure resource group
  azure_rm_resourcegroup:
    name: "Student{{item}}"
    location: "{{ region }}"
    tags:
        Linklight: "This was provisioned through the linklight provisioner"
        Students: "{{ student_total }}"
  with_sequence: start=1 end="{{ student_total }}"
  register: resource_group
